apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
     - ./infra/k8s/*
     - ./infra/k8s-dev/*
build:
  #local:
    #push: false
  googleCloudBuild:
    projectId: ticketing-dev-395421   
  artifacts:
    - image: us.gcr.io/ticketing-dev-395421/auth
    #- image: rajivhere/auth
      context: auth
      docker:
       dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .    
    - image: us.gcr.io/ticketing-dev-395421/client
    #- image: rajivhere/client
      context: client
      docker:
       dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: us.gcr.io/ticketing-dev-395421/tickets
    #- image: rajivhere/tickets
      context: tickets
      docker:
       dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-395421/orders
    #- image: rajivhere/orders
      context: orders
      docker:
       dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-395421/expiration
    #- image: rajivhere/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-395421/payments
    #- image: rajivhere/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
            
  
