name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t rajivhere/auth .
      
      
